/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root"
import { Route as SignupRouteImport } from "./routes/signup"
import { Route as SettingsRouteImport } from "./routes/settings"
import { Route as LoginRouteImport } from "./routes/login"
import { Route as DashboardRouteImport } from "./routes/dashboard"
import { Route as CreateRouteImport } from "./routes/create"
import { Route as IndexRouteImport } from "./routes/index"
import { Route as PollPollIdRouteImport } from "./routes/poll/$pollId"
import { Route as AnalyticsPollIdRouteImport } from "./routes/analytics/$pollId"

const SignupRoute = SignupRouteImport.update({
  id: "/signup",
  path: "/signup",
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: "/settings",
  path: "/settings",
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: "/login",
  path: "/login",
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: "/dashboard",
  path: "/dashboard",
  getParentRoute: () => rootRouteImport,
} as any)
const CreateRoute = CreateRouteImport.update({
  id: "/create",
  path: "/create",
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any)
const PollPollIdRoute = PollPollIdRouteImport.update({
  id: "/poll/$pollId",
  path: "/poll/$pollId",
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsPollIdRoute = AnalyticsPollIdRouteImport.update({
  id: "/analytics/$pollId",
  path: "/analytics/$pollId",
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute
  "/create": typeof CreateRoute
  "/dashboard": typeof DashboardRoute
  "/login": typeof LoginRoute
  "/settings": typeof SettingsRoute
  "/signup": typeof SignupRoute
  "/analytics/$pollId": typeof AnalyticsPollIdRoute
  "/poll/$pollId": typeof PollPollIdRoute
}
export interface FileRoutesByTo {
  "/": typeof IndexRoute
  "/create": typeof CreateRoute
  "/dashboard": typeof DashboardRoute
  "/login": typeof LoginRoute
  "/settings": typeof SettingsRoute
  "/signup": typeof SignupRoute
  "/analytics/$pollId": typeof AnalyticsPollIdRoute
  "/poll/$pollId": typeof PollPollIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  "/": typeof IndexRoute
  "/create": typeof CreateRoute
  "/dashboard": typeof DashboardRoute
  "/login": typeof LoginRoute
  "/settings": typeof SettingsRoute
  "/signup": typeof SignupRoute
  "/analytics/$pollId": typeof AnalyticsPollIdRoute
  "/poll/$pollId": typeof PollPollIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | "/"
    | "/create"
    | "/dashboard"
    | "/login"
    | "/settings"
    | "/signup"
    | "/analytics/$pollId"
    | "/poll/$pollId"
  fileRoutesByTo: FileRoutesByTo
  to:
    | "/"
    | "/create"
    | "/dashboard"
    | "/login"
    | "/settings"
    | "/signup"
    | "/analytics/$pollId"
    | "/poll/$pollId"
  id:
    | "__root__"
    | "/"
    | "/create"
    | "/dashboard"
    | "/login"
    | "/settings"
    | "/signup"
    | "/analytics/$pollId"
    | "/poll/$pollId"
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CreateRoute: typeof CreateRoute
  DashboardRoute: typeof DashboardRoute
  LoginRoute: typeof LoginRoute
  SettingsRoute: typeof SettingsRoute
  SignupRoute: typeof SignupRoute
  AnalyticsPollIdRoute: typeof AnalyticsPollIdRoute
  PollPollIdRoute: typeof PollPollIdRoute
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/signup": {
      id: "/signup"
      path: "/signup"
      fullPath: "/signup"
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/settings": {
      id: "/settings"
      path: "/settings"
      fullPath: "/settings"
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/login": {
      id: "/login"
      path: "/login"
      fullPath: "/login"
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/dashboard": {
      id: "/dashboard"
      path: "/dashboard"
      fullPath: "/dashboard"
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/create": {
      id: "/create"
      path: "/create"
      fullPath: "/create"
      preLoaderRoute: typeof CreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/": {
      id: "/"
      path: "/"
      fullPath: "/"
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/poll/$pollId": {
      id: "/poll/$pollId"
      path: "/poll/$pollId"
      fullPath: "/poll/$pollId"
      preLoaderRoute: typeof PollPollIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/analytics/$pollId": {
      id: "/analytics/$pollId"
      path: "/analytics/$pollId"
      fullPath: "/analytics/$pollId"
      preLoaderRoute: typeof AnalyticsPollIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CreateRoute: CreateRoute,
  DashboardRoute: DashboardRoute,
  LoginRoute: LoginRoute,
  SettingsRoute: SettingsRoute,
  SignupRoute: SignupRoute,
  AnalyticsPollIdRoute: AnalyticsPollIdRoute,
  PollPollIdRoute: PollPollIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
